name: pymmc_w_stardist
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10
  - pandas
  - numpy<2
  - pyarrow
  - ipykernel
  - ipywidgets
  - matplotlib
  - napari
  - scikit-image
  - pyqt
  - tifffile
  - pip
  - pip: 
    - git+https://github.com/alandolt/pymmcore-plus.git@feat--include-useq-properties-in-mda-engine
    - pymmcore-widgets
    - tensorflow
    - stardist
    - csbdeep
    - trackpy