name: pymmc_w_stardist
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10
  - pandas
  - numpy<2
  - pyarrow
  - ipykernel
  - ipywidgets
  - matplotlib
  - napari
  - scikit-image
  - pyqt
  - tifffile
  - pip
  - pip: 
    - pymmcore-plus
    - pymmcore-widgets
    - tensorflow
    - stardist
    - csbdeep
    - trackpy