name: napari
channels:
  - defaults
  - conda-forge
dependencies:
  - napari
  - pandas
  - pyarrow
  - magicgui
  - tifffile
  - dask
  - scikit-image
  - numpy
  - ipykernel
  - opencv
  - pip
  - pip:
    - napari-timestamper
